'use server';

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';

/**
 * Claims the username the user picked at signup. Runs on first login after
 * email confirmation (and harmlessly on Google OAuth first login) before the
 * DB trigger's auto-generated username can be saved.
 */
export async function ensureUsernameForUser() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  const { data: profile } = await supabase
    .from('profiles')
    .select('username, display_name, avatar_url, user_id')
    .eq('user_id', user.id)
    .single();

  // Profile missing → DB trigger hasn't run yet (or RLS hid it). Nothing to do.
  if (!profile) return { error: 'Profile not found' };

  const claimed = user.user_metadata?.username as string | undefined;
  const isAutoGenerated =
    profile.username === (user.email ?? '').split('@')[0] ||
    /-\w{4}$/.test(profile.username);

  const googleName = user.user_metadata?.full_name || user.user_metadata?.name;
  const googleAvatar = user.user_metadata?.avatar_url || user.user_metadata?.picture;

  const updates: Record<string, any> = {};
  if (claimed && isAutoGenerated) {
    updates.username = claimed;
  }
  if (googleName && (!profile.display_name || profile.display_name === profile.username)) {
    updates.display_name = googleName;
  }
  if (googleAvatar && !profile.avatar_url) {
    updates.avatar_url = googleAvatar;
  }

  if (Object.keys(updates).length > 0) {
    const { error } = await supabase
      .from('profiles')
      .update(updates)
      .eq('user_id', user.id);

    if (error) return { error: error.message };
  }

  revalidatePath('/dashboard');
  if (claimed) revalidatePath(`/${claimed}`);
  return { success: true };
}
