'use server';

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';

/**
 * Claims the username the user picked at signup. Runs on first login after
 * email confirmation (and harmlessly on Google OAuth first login) before the
 * DB trigger's auto-generated username can be saved.
 */
export async function ensureUsernameForUser() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  const { data: profile } = await supabase
    .from('profiles')
    .select('username, user_id')
    .eq('user_id', user.id)
    .single();

  // Profile missing → DB trigger hasn't run yet (or RLS hid it). Nothing to do.
  if (!profile) return { error: 'Profile not found' };

  const claimed = user.user_metadata?.username as string | undefined;
  if (!claimed) return { success: true };

  const isAutoGenerated =
    profile.username === (user.email ?? '').split('@')[0] ||
    /-\w{4}$/.test(profile.username);

  if (!isAutoGenerated) return { success: true };

  const { error } = await supabase
    .from('profiles')
    .update({ username: claimed })
    .eq('user_id', user.id);

  if (error) return { error: error.message };

  revalidatePath('/dashboard');
  revalidatePath(`/${claimed}`);
  return { success: true };
}
